title: <p align="center"> Kiran Kumar Valluru </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/kirankumarvalluru/">LinkedIn</a> |
  <a href="https://github.com/valluruK">GitHub</a>
  
  <br>   
  I'm working on SAP with specialization in Insurance industry from past 11 years.
  Also exploring on Machine learning and addressing the related problems.
  <br>
  </p>
  
theme: jekyll-theme-minimal
